# Generated by Django 4.1.6 on 2023-03-25 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('other', 'разное'), ('technique', 'техника'), ('cloth', 'одежда'), ('toys', 'игрушки')], default='other', max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2000, null=True, verbose_name='Текст')),
                ('iis_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('image_url', models.TextField(max_length=3000, null=True, verbose_name='Фото')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_at', models.DateTimeField(default=None, null=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateField(default=None, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=3000, null=True, verbose_name='Текст Коментария')),
                ('grade', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='webapp.product', verbose_name='Продукт')),
                ('users', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
